from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


def generate_pdf(summary, health_score, quality_score, filename):

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    heading = styles["Heading2"]
    normal = styles["BodyText"]

    doc = SimpleDocTemplate(
        filename,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    story = []

    # ==========================================
    # Cover
    # ==========================================

    story.append(
        Paragraph(
            "🧹 CleanIQ",
            title
        )
    )

    story.append(
        Paragraph(
            "AI Powered Data Quality Report",
            heading
        )
    )

    story.append(Spacer(1, 0.35 * inch))


    # ==========================================
    # Dataset Summary
    # ==========================================

    story.append(
    Paragraph(
        "<b>Dataset Summary</b>",
        heading
    )
)

    table_data = [

    ["Metric", "Value"],

    ["Rows", str(summary["Rows"])],

    ["Columns", str(summary["Columns"])],

    ["Missing Values", str(summary["Missing Values"])],

    ["Duplicate Rows", str(summary["Duplicate Rows"])],

    ["Health Score", f"{health_score}/100"],

    ["Quality Score", f"{quality_score}%"]

]

    table = Table(
    table_data,
    colWidths=[220, 180]
)

    table.setStyle(

    TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#2563eb")),

        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

        ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0,0), (-1,0), 10),

        ("ALIGN", (0,0), (-1,-1), "CENTER")

    ])

)

    story.append(table)

    story.append(Spacer(1, 0.3 * inch))

    # ==========================================
    # AI Recommendation
    # ==========================================

    story.append(
    Paragraph(
        "<b>AI Recommendation</b>",
        heading
    )
)

    if quality_score >= 90:

     recommendation = """
Dataset quality is excellent.
The dataset is ready for analytics and Machine Learning.
"""

    elif quality_score >= 70:

     recommendation = """
Dataset quality is good.
A little cleaning is recommended before ML training.
"""

    else:

     recommendation = """
Dataset quality is poor.
Clean missing values and duplicate records before using the dataset.
"""

    story.append(
    Paragraph(
        recommendation,
        normal
    )
)

    story.append(Spacer(1, 0.3 * inch))

    # ==========================================
    # Footer
    # ==========================================

    story.append(
    Paragraph(
        "<b>Generated by CleanIQ v3.0</b>",
        heading
    )
)

    story.append(
    Paragraph(
        "Developer : Aaditya Malviya",
        normal
    )
)

    story.append(
    Paragraph(
        "MBA Business Analytics & AI",
        normal
    )
)

    story.append(
    Paragraph(
        "Generated automatically using CleanIQ AI Platform.",
        normal
    )
)

    doc.build(story)
